### ISSUE TITLE
Icon size is too small (i.e. low quality desktop app icon)

### ISSUE THREAD

**Issue by machitgarha** [ferion11/atom_Appimage#1]
Initially, thanks for providing Atom AppImage here. Really.

The issue is all about the app's icon. Quality is just too low, and I'm not happy with it. Its size does not reach even 1KB! I think this should be changed into a high-quality icon instead, shouldn't it?

I wonder if there is a licensing or copyright problem(s) with the original logo; so please let me (us) if there are any.

Thanks.

**Comment by ferion11** [comment]
Well, I changed the current icon from 16x16 to 128x128 now. This should be enough, I guess:
02e139f7f9a9a7e145717389d7870cc40c5c49c7

**Comment by machitgarha** [comment]
Well, perfect! Thanks for the change, and thanks for your early response!
