### ISSUE TITLE
Embedded update information

### ISSUE THREAD

**Issue by machitgarha** [ferion11/atom_Appimage#2]
As you might know, AppImages could have [embedded update information](https://github.com/AppImage/AppImageUpdate). Currently, the only way to update is to download the new version and replace it with the old one. However, with that information provided within the AppImage, we benefit from updating it more easily (and also with less network usage).

**Comment by ferion11** [comment]
> As you might know, AppImages could have [embedded update information](https://github.com/AppImage/AppImageUpdate). Currently, the only way to update is to download the new version and replace it with the old one. However, with that information provided within the AppImage, we benefit from updating it more easily (and also with less network usage).

As far as I remember the only thing I needed to do was generate the zsync file. The configuration for the integration would be done by the user himself. But maybe I got it wrong. Since I use FluxBox, I ended up not testing these integrations.

**Comment by machitgarha** [comment]
Sorry, but the update process is still broken. This issue should be reopened.
