### ISSUE TITLE
Build Atom for versions 1.59+

### ISSUE THREAD

**Issue by machitgarha** [ferion11/atom_Appimage#9]
Currently, no release is made for versions above 1.58. Releasing them until the latest official release (1.63) is a good idea.

**Comment by ferion11** [comment]
The v1.63.0 was released today, so I updated the AppImage too:
https://github.com/ferion11/atom_Appimage/releases

The non release (not tested) last version is always on:
https://github.com/ferion11/atom_Appimage/releases/tag/continuous-master

**Comment by machitgarha** [comment]
Although having release between 1.59 to 1.62 is good IMO, but thanks.

**Comment by machitgarha** [comment]
Although having release between 1.59 to 1.62 is good IMO, but thanks.
